version: '3'

# network shared between containers
networks:
  bridge-network:
    driver: bridge

services:
  api:
    container_name: api
    build:
      # context: you should put the root path of the project
      # this affect on Dockerfile also
      context: ../../.
      dockerfile: docker/dockerfiles/development.Dockerfile
    restart: always
#   command: sh ./docker/commands.sh
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.development
      - REDIS_URL=redis://redis:6379/0
      - REDIS_DB=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    networks:
      - bridge-network

  redis:
    container_name: redis-server
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - bridge-network

  celery:
    restart: always
    build:
      context: ../../.
      dockerfile: docker/dockerfiles/development.Dockerfile
    command: celery -A api worker -l info
    volumes:
      - celery:/code
    container_name: celery
    # it is need postgres environments for get objects from database
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
      - api
    networks:
      - bridge-network


volumes:
  celery: