version: '3.5'

# network shared between containers
networks:
    net:
      name: api_network
      driver: bridge

services:
  api:
    container_name: api
    depends_on:
      - db
    build:
      # context: you should put the root path of the project
      # this affect on Dockerfile also
      context: ../../.
      dockerfile: docker/dockerfiles/production.Dockerfile
    restart: always
#   command: sh ./docker/commands.sh
    volumes:
      - api-data:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HOST=db
      - PORT=5432
      - DJANGO_SETTINGS_MODULE=api.settings.production
      - REDIS_URL=redis://redis:6379/0
      - REDIS_DB=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379


    networks:
      - net


  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net

  redis:
    container_name: redis-server
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - net

  celery:
    restart: always
    build:
      context: ../../.
      dockerfile: docker/dockerfiles/development.Dockerfile
    command: celery -A api worker -l info
    volumes:
      - celery:/code
    container_name: celery
    # it is need postgres environments for get objects from database
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HOST=db
      - PORT=5432
      - DJANGO_SETTINGS_MODULE=api.settings.production

    depends_on:
      - redis
      - api
      - db
    networks:
      - net


volumes:
  db:
  api-data:
  celery: