version: '3.5'


networks:
    frontend-net:
        name: api_network  # for use the network which created in the api compose file
        external: true  # for search on external network with name: api_network


services:
  frontend:
    container_name: frontend
    build: .
    restart: always
#   command: sh commands.sh
    ports:
      - "6123:6123"
    volumes:
      - frontend-data:/code
    networks:  # same network of the api
      - frontend-net

volumes:
  frontend-data:
